services:

  mysql:
    image: mysql:8
    container_name: invoice_mysql

    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: invoice_db

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10  

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: invoice_backend

    restart: always

    ports:
      - "5000:5000"

    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: invoice_frontend

    ports:
      - "5173:80"

    depends_on:
      - backend

volumes:
  mysql_data: